'use client';
import '../styles/globals.css';
import { SessionProvider } from 'next-auth/react';
// export const metadata = {
// 	title: 'Next.js',
// 	description: 'Generated by Next.js',
// };

interface IProps {
	children: React.ReactNode;
	session: any;
}

export default function RootLayout({ children, session }: IProps) {
	return (
		<html lang="en">
			<body className="bg-[#F2F2ED]">
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
